### ISSUE TITLE
unable to use client certificate

### ISSUE THREAD

**Issue by rogerwang** [thojansen/client-certificates#1]
I'm trying the 4th step but it failed:

```
$ curl -v --cert ./ssl/client.p12:test --cacert ssl/rootCA.crt https://localhost:5000/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
* unable to use client certificate (no key found or wrong pass phrase?)
* Closing connection 0
curl: (58) unable to use client certificate (no key found or wrong pass phrase?)
```

**Comment by rogerwang** [comment]
btw, I used `test` as password when I ran setup.sh

**Comment by thojansen** [comment]
..that is strange.. looks as if the p12 was not created right. i have pushed some sample keys with https://github.com/thojansen/client-certificates/commit/7d967dc9369a3a0a54ae756409e4bd53b641c63a .. can you check with these?

**Comment by rogerwang** [comment]
it didn't work. but I skipped that and finished the steps with browser successfully.
